### PR TITLE
Reworked the UI for the main website, created an automated process to link individual profiles, reorganized the project structure.

### PR DESCRIPTION
**Pull request by ozanmirza1**
I made a copy of the website and changed up the UI. The content is still the same, just a little more modern with some animations. I also changed the way people can add their links. Instead of hard-coded adding their own elements to the HTML, they can add their name to a data variable in the main.js file that then includes it and updates the dropdown automatically. There is also documentation for how and where to add their information inside the main.js file and explains how the classes and methods create the elements. I reorganized a bit of the structure, leaving the confusing parts for the entire class to discuss an optimal and efficient way of taking care of it. I added and coded my portfolio page. I thought that if the teachers have their own designated folders and an organized project structure there, then the entire structure could be neater. I made sure that all relative links and assets were still connected. However, this can also be temporary and we can redistribute the files to the different group folders just as they were.

### CODE REVIEW

**Comment by elindow** [comment]
This sounds great. Robert created a previous pull request, not merged yet, that moved last year’s grads into a 2020 folder. Do you think your changes will conflict with Robert’s menu changes? If so I can investigate more before doing the pulls and/or just not do Robert’s pull.

**Comment by ozanmirza1** [comment]
After looking at what files were changed, I think that you can close his pull request without merging because it deals with the menu, and this pull request changes that entire menu system in the page.

**Comment by elindow** [comment]
Yes, that makes sense to me.

**Comment by elindow** [comment]
Also, is your APW repo set up so the web page can display there with github.io?  I would have liked to be able to check it out immediately there, even before I did the pull, which is now done but takes a while to propagate. Your site with the corresponding link told me the page didn’t exist. If the pages are setup there with a different link I couldn’t find where listed in the repo.

**Comment by ozanmirza1** [comment]
I just went on the github.io <http://github.io/> site and checked my link, it is working correctly.

**Comment by elindow** [comment]
What’s the correct link to see the resulting main page of your fork of the APW1 project?

**Pull request merged**
